[Unit]
After=greetd.service

[Service]
ExecStart=
ExecStart=-/usr/bin/plymouth quit --retain-splash
ExecStartPre=/bin/bash -c 'for i in $(seq 1 30); do pgrep -x Hyprland >/dev/null && break; sleep 0.5; done; sleep 1'
